### ISSUE TITLE
Setting up the application 

### ISSUE THREAD

**Issue by jareksgit** [nag763/tchatchers#4]
**Is your feature request related to a problem? Please describe.**
I am having trouble setting up the project in a local environment and in a Docker container, specifically with configuring the Postgres host.

**Describe the solution you'd like**
I would like to have clear and concise installation guides that provide instructions on how to set up the project both locally and in a Docker container, including how to properly configure the Postgres host.

**Describe alternatives you've considered**
I have not considered any alternatives as I am not familiar with how to set up the project properly.

**Additional context**
The Postgres host seems to be hardcoded in tchatchers_core/src/pool.rs, and it would be helpful to have instructions on how to configure it properly in the installation guides. 
Thank you for your great work on this project :-)

**Comment by nag763** [comment]
Hello @jareksgit , thanks for your issue, :+1: 

The documentation will be enhanced and additional tools will be provided so that the setup is made easier for people who want to install the application both in dev mode and production.

You will be made aware of the advancements on this thread :)

**Comment by jareksgit** [comment]
That sounds great,
thank you for the updates and for working to make the installation process easier for the community. 
Keep up the good work!

**Comment by nag763** [comment]
Thanks ! 

Please just use this for learning or testing purposes, it isn't really intended to be used in a production server or whatever.

I will try to provide the following tools in the documentation regard : 

- [ ]  Dedicated installation section in readme.
- [ ]  Documentation enhancement (in progress).
- [ ]  README and architecture schemas update.
- [ ]  Ability to generate a _.env_
- [ ]  Administrative cli-tools to be used on server.

**Comment by nag763** [comment]
Adding a cargo make script to install from a very fresh distro could be helpful

**Comment by nag763** [comment]
Hello @jareksgit  ! 

I invite you to use the following : 
* Set up doc : https://github.com/nag763/tchatchers/blob/main/SETUP.md
* CLI Tools to manage your app once running : https://github.com/nag763/tchatchers/tree/main/tchatchers_cli_tools
=> Run with cargo r --bin tct inside the project

Technical and functionnal doc will be updated and made available quite soon I hope :)

Lmk if you face any further issue :+1:
